### ISSUE TITLE
Add rule for separating assert into one line per keyword

### ISSUE THREAD

**Issue by staerz** [jeremiah-c-leary/vhdl-style-guide#548] opened 2021-03-30 19:31 UTC
**Is your feature request related to a problem? Please describe.**
It is simply a style preference

**Describe the solution you'd like**
There are a few rules on formatting asserts already and all them assume the assert to be split over multiple lines, having each line starting with the respective keyword:
```vhdl
assert <condition>
  report <message>
  severity <level>
```
but in fact there is no rule that checks that the keywords `report` and `severity` are actually on a separate line.

Hence an (optional = disabled by default?)) rule should be added that ensures this.

Of course, the keywords `report` and `severity` must also be indented as in the example, following the global indentation rules.

**Describe alternatives you've considered**
Just don't care for this rule.

**Comment by jeremiah-c-leary** [comment] 2021-03-31 13:05
Hey @staerz,

I added some rules to move the keywords to a new line.  I pushed an update to the issue-548 branch.

Let me know what you think.

--Jeremy

**Comment by staerz** [comment] 2021-03-31 13:57
Hi @jeremiah-c-leary,

I tried it and I had it run over my code base.

Messages for assert_003 and 5 are very clear, except it should be "its", not "it's" :wink:

Then I let vsg run with the `--fix` option and funny things happen:
```diff
         if (OUTPUT_INVERT) then
-          assert (sel_o(4 downto 0) = "11000") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0) = "11000")
+            reportreportreportreport "Result wrong"
+            severityseverityseverityseverity warning;
         else
-          assert (sel_o(4 downto 0) = "00111") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0) =)
+            report            report            report"Result wrong"
+            severity            severity            severityseverity warning;
         end if;
```

```diff
         if (OUTPUT_INVERT) then
-          assert (sel_o(4 downto 0) = "11001") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0))
+            report
+            report            "Result wrong"
+            severity
+            severity            severityseverity warning;
         else
-          assert (sel_o(4 downto 0) = "00110") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0))
+            report
+            report"Result wrong"
+            severity
+            severity            severity warning;
         end if;
```


```diff
         if (OUTPUT_INVERT) then
-          assert (sel_o(4 downto 0) = "01001") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0) =)
+              report
+              "Result wrong"
+            severity
+            severity warning;
         else
-          assert (sel_o(4 downto 0) = "10110") report "Result wrong" severity warning;
+          assert (sel_o(4 downto 0) = "10110")
+            report "Result wrong"
+            severity warning;
         end if;
```


and also 

```diff
-    x"--" when others;
-
+    x
```

Honestly, no clue where the last diff comes from, I could dig a bit but would leave this to the next iteration (of this issue) if you don't mind.

**Comment by jeremiah-c-leary** [comment] 2021-03-31 15:20
That is bizarre.  I will make a test case.

**Comment by jeremiah-c-leary** [comment] 2021-03-31 15:27
I have this snippet:
```vhdl
  1
  2 architecture rtl of fifo is
  3
  4 begin
  5
  6   proc_label: process (blah
  7   ) is begin
  8
  9     if (OUTPUT_INVERT) then
 10       assert (sel_0(4 downto 0) = "11000") report "Result wrong" severity warning;
 11     else
 12       assert (sel_0(4 downto 0) = "00111") report "Result wrong" severity warning;
 13     end if;
 14
 15   end process proc_label;
 16
 17 end architecture rtl;
```
...and when I apply the `--fix` I get this:
```vhdl
  1
  2 architecture rtl of fifo is
  3
  4 begin
  5
  6   proc_label: process (blah
  7   ) is begin
  8
  9     if (OUTPUT_INVERT) then
 10       assert (sel_0(4 downto 0) = "11000") report "Result wrong" severity warning;
 11     else
 12       assert (sel_0(4 downto 0) = "00111") report "Result wrong" severity warning;
 13     end if;
 14
 15   end process proc_label;
 16
 17 end architecture rtl;
```
I think this is the third issue where we have different behavior between us.  Is there something fundamentally different in our environments?

**Comment by jeremiah-c-leary** [comment] 2021-04-07 13:56
Hey @staerz,

Just wanted to ping you and see if you had a chance to look at my response.

--Jeremy

**Comment by staerz** [comment] 2021-04-07 14:47
Hi @jeremiah-c-leary,

I'm running VSG with Python 3.8.7 on a Fedora 32.

And I just checked again, the behaviour when I run with the `--fix` option is still the same (which doesn't surprise me as there's no new commit).

But I think the problem here is actually the line
```vhdl
    x"--" when others;
```
which is in the context of a `with counter select <8 bit signal> <= ` statement which you don't have in your code (I remember your `with_001` - so you don't properly parse these it seems.
On that line I get a complaint from `concurrent_010`:

```
  concurrent_010            | Error      |        251 | Remove blank line
```
So this also seems what the `--fix` then is somehow getting wrong, together with some other stuff, as if I manually fix the complaints on `assert_003` and 5, that's the remaining complaint.

If I change the line to
```vhdl
    x"-" when others;
```
(which is wrong, of course) then vsg passes without complaints after having manually fixed the complaints, but still an auto-fix results in those strange duplicates in some cases.

So not really sure how to proceed here.

**Comment by jeremiah-c-leary** [comment] 2021-04-07 18:06
Hey @staerz ,
I bet my comment detection is kicking in.

**Comment by jeremiah-c-leary** [comment] 2021-04-08 02:08
Hey @staerz,

I believe I fixed this issue.  However, I committed the change to master instead of the issue-548 branch.

If you could update to master and merge in the issue-548 branch as you normally do, it should have the same affect.

Thanks,

--Jeremy

**Comment by staerz** [comment] 2021-04-08 13:48
Hi @jeremiah-c-leary,

so I did what you asked, pulled master and merged issue-548 into it and then run my VSG again.

I'm sorry to tell you, but it doesn't change anything.

Have you noticed that the `--fix` is altering the assert condition (examples above)?

When I look at my example more closely and compare it to yours, I see the following differences: I have 4 asserts while you only have 2.

In the correction to my asserts, it looks like a counter would increase and put as many `report` and `severity` keywords: The very last instance is fixed properly, the second-last has  `severity` and `report` twice, the third-last has `severity` and `report` 3 times, etc.

**Comment by jeremiah-c-leary** [comment] 2021-04-22 00:31
Hey @staerz,

hmm...I will take a look at it again this weekend.

--Jeremy

**Comment by jeremiah-c-leary** [comment] 2021-04-22 01:40
Hey @staerz,

I decided to merge issue-548 branch into master because there was a commit for issue-542 on that branch.  Could you try pulling down a new master and check again if the issue remains?

Thanks,

--Jeremy

**Comment by jeremiah-c-leary** [comment] 2021-04-23 00:51
Hey @staerz,

Is there a chance you could create a minimal file that shows the issue?  I have tried to recreate what I think your code looks like, but I do not see the duplication issue.

Thanks,

--Jeremy

**Comment by jeremiah-c-leary** [comment] 2021-09-18 13:57
Hey @staerz ,

I am just getting back into this project.  I was wondering if we could pick this issue back up.

**Comment by staerz** [comment] 2021-09-20 14:54
Hi @jeremiah-c-leary,

I'm attaching you the original file which produced that funny behaviour.

Note that I'm still running VSG 3.0.0 and I saw that newer versions are out.
I didn't have any time to further look into our open issues but would be happy to pick them up where we left them.
I can though not promise anything.

[fpga_top_tb.txt](https://github.com/jeremiah-c-leary/vhdl-style-guide/files/7196565/fpga_top_tb.txt)

**Comment by jeremiah-c-leary** [comment] 2021-09-22 01:52
I can see VSG messing up the code.

I copied  a snippet of your example into my tests and it is fixed correctly.

I also ran your example with a configuration where I disable all rules except for `assert_005`, and it still messes up.

Still investigating.

**Comment by jeremiah-c-leary** [comment] 2021-09-22 03:08
I have a fix for the problem, but I need to update the other assert rules and their tests.

**Comment by jeremiah-c-leary** [comment] 2021-09-22 03:31
Hey @staerz ,

I just pushed a fix that works on the file you sent.  If you get a chance, could you check it on your end?

--Jeremy

**Comment by staerz** [comment] 2021-09-23 13:08
Hi @jeremiah-c-leary,

I have installed the latest version for it - I assume that the branch `issue-548` is the correct one.

Unfortunately, I still get a this strange behaviour of repeated keywords.

I attach you the diff that I get when running VSG with the `--fix` option:
[vsg_fix.txt](https://github.com/jeremiah-c-leary/vhdl-style-guide/files/7217803/vsg_fix.txt)

For completeness, here is the VSG configuration:
[vsg.zip](https://github.com/jeremiah-c-leary/vhdl-style-guide/files/7217820/vsg.zip)

In order to run VSG on our source base, we simply call `vsg $(cat .vsg/params.txt)` as the full parameter line is in this `params.txt` which you'll find in the zip archive.
To do so, please rename the directory inside the archive to `.vsg` or create a softlink `.vsg` pointing to the contained directory (`.vsg_local`).

I hope that would help you replicate the issue on your side.

**Comment by jeremiah-c-leary** [comment] 2021-09-25 02:29
Hey @staerz,

> I have installed the latest version for it - I assume that the branch issue-548 is the correct one.

Let's chalk this one up to my poor communication skills and being rusty coming back.

I ended up making the change on master as I forgot I had a branch and did not even check my branches to see if issue-548 exists.  So I ended up updated and pushing to master.

Could you check out the latest on master and see if the issue is resolved?

Thanks,

--Jeremy

**Comment by staerz** [comment] 2021-09-27 17:06
Hi @jeremiah-c-leary,

alright. I have just run it with the latest master version and can now confirm that I don't see any of these strange duplicates and instead the indentation now is as intended.

Nevertheless, double-checking also the past of this thread, you still have a typo in the message spit by the asserts:
```
  assert_003                | Error      |        155 | Place **report** keyword on it's own line.
  assert_005                | Error      |        155 | Place **severity** keyword on it's own line.
```
Note that it should be `its` and not `it's`.
I guess that this would apply not only for 003 and 005 but also for 002 and 004.

**Comment by staerz** [comment] 2021-09-28 13:14
Hi @jeremiah-c-leary,

yes, that's well done, thanks!

The pleasure of closing the issue is yours!

**Closed** 2021-09-29 11:51 UTC
Labels: enhancement
