### ISSUE TITLE
VSG crashes upon encountering empty comment in entity declaration

### ISSUE THREAD

**Issue by staerz** [jeremiah-c-leary/vhdl-style-guide#547] opened 2021-03-29 17:03 UTC
**Environment**
VSG 3.0.0.

**Describe the bug**
VSG crashes upon encountering empty comment in entity declaration.

In particular it will crash with the following error:
```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sam/.local/lib/python3.6/site-packages/vsg/__main__.py", line 469, in apply_rules
    oRules.check_rules(bAllPhases=commandLineArguments.all_phases, lSkipPhase=commandLineArguments.skip_phase)
  File "/home/sam/.local/lib/python3.6/site-packages/vsg/rule_list.py", line 217, in check_rules
    oRule.analyze(self.oVhdlFile)
  File "/home/sam/.local/lib/python3.6/site-packages/vsg/rules/block_comment/rule_002.py", line 50, in analyze
    if not is_header(oToken.get_value()):
  File "/home/sam/.local/lib/python3.6/site-packages/vsg/rules/block_comment/rule_002.py", line 80, in is_header
    if sComment[2] not in string.punctuation:
IndexError: string index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sam/.local/bin/vsg", line 11, in <module>
    sys.exit(main())
  File "/home/sam/.local/lib/python3.6/site-packages/vsg/__main__.py", line 412, in main
    for tResult in pool.imap(f, enumerate(commandLineArguments.filename)):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 735, in next
    raise value
IndexError: string index out of range
```
when running on the following code snippet:
```vhdl
    inst_dummy : entity lib.module
    port map (
      -- Clocks
      clk   => clk
      --
      -- Dummy comment
      --
      data_i => data_i
    );
```

It doesn't seem to be every empty comment, just ones that follow this pattern (and only in entity declarations):
The comment with an empty comment above and an empty comment below.

**To Reproduce**
1. Run VSG on the above code snippet
1. See error

**Expected behavior**
VSG should not crash.

**Comment by jeremiah-c-leary** [comment] 2021-03-29 20:32
Hey @stears,

I looks like my block comment detector is having an issue.

--jeremy

**Comment by jeremiah-c-leary** [comment] 2021-03-29 22:43
Hey @staerz,

I used this snippet:
```vhdl
  1
  2 architecture rtl of fifo is
  3
  4 begin
  5
  6   inst_dummy : entity lib.module
  7     port map (
  8       -- Clocks
  9       clk => clk
 10       --
 11       -- Dummy comment
 12       --
 13       data_i => data_i
 14     );
 15
 16 end architecture rtl;
```
with this configuration:
```yaml
  1 rule:
  2    instantiation_034:
  3       disable : True
  4    block_comment_001:
  5       disable : False
  6       allow_indenting : False
  7       header_left : '+'
  8       header_right_repeat : '='
  9       header_string : '[ Header ]'
 10       max_header_column : 40
 11    block_comment_002:
 12       disable : False
 13       allow_indenting : False
 14       comment_left : '|'
 15    block_comment_003:
 16       disable : False
 17       allow_indenting : False
 18       max_footer_column : 40
```
and it does not crash.

I also tried adding this configuration for indenting:
```json
  1 {
  2   "indent": {
  3     "tokens": {
  4       "port_map_aspect": {
  5         "port_keyword": {
  6           "after": "current",
  7           "token": "-1"
  8         }
  9       }
 10     }
 11   }
 12 }
```
and it did not crash.

Could it possibly be something in your configuration?

I also noticed the comma was missing after `clk => clk`.

**Comment by staerz** [comment] 2021-03-29 22:53
Hi @jeremiah-c-leary,

OK, so here is our configuration (I couldn't find a better way than simply c&p here):

```json
{
  "indent":{
    "tokens":{
      "component_instantiation_statement":{
        "instantiation_label":{
          "token" : "current",
          "after" : "current",
        },
        "semicolon":{
          "token" : "current",
          "after" : "current",
        },
      },
    },
  },
  "rule":{
    "architecture_003": {
      "style":"require_comment"
    },
    "architecture_010":{
      "action":"add",
    },
    "architecture_015":{
      "style":"require_blank_line"
    },
    "architecture_016":{
      "style":"require_blank_line"
    },
    "architecture_017":{
      "style":"require_blank_line"
    },
    "architecture_018":{
      "style":"require_blank_line"
    },
    "architecture_025":{
      "disable":false,
      "names":[
        "behavioral",
        "emulational",
        "empty",
        "tb",
      ],
    },
    "assert_400":{
      "alignment":"left",
    },
    "block_002":{
      "action":"remove"
    },
    "block_007":{
      "action":"add"
    },
    "block_200":{
      "style":"allow_comment"
    },
    "block_201":{
      "style":"no_blank_line"
    },
    "block_202":{
      "style":"no_blank_line"
    },
    "block_203":{
      "style":"require_blank_line"
    },
    "block_204":{
      "style":"require_blank_line"
    },
    "block_601":{
      "disable":false,
    },
    "block_comment_001":{
      "disable": false,
      "header_left_repeat": "-",
      "header_string": "<-    80 chars    ->",
      "header_right_repeat": "-",
      "max_header_column": 80,
      "allow_indenting": false,
    },
    "block_comment_002":{
      "disable": false,
    },
    "block_comment_003":{
      "disable": false,
      "max_footer_column": 80,
      "allow_indenting": false,
    },
    "case_007":{
      "style":"allow_comment"
    },
    "concurrent_003":{
      "new_line_after_assign":"yes",
      "ignore_single_line":"yes",
      "align_left": "yes"
    },
    "concurrent_009":{
      "align_left": "yes",
      "align_paren": "yes",
      "align_when_keywords": "no",
      "wrap_at_when": "yes",
      "align_else_keywords": "no",
    },
    "concurrent_011":{
      "new_line_after_assign":"yes",
      "ignore_single_line":"yes"
    },
    "component_003":{
      "style":"allow_comment"
    },
    "concurrent_007":{
      "allow_single_line":true
    },
    "constant_012":{
      "align_left":true,
      "align_paren":false
    },
    "constant_016":{
      "first_paren_new_line":"yes",
      "last_paren_new_line":"yes",
      "open_paren_new_line":"yes",
      "close_paren_new_line":"yes",
      "new_line_after_comma":"ignore_positional",
      "assign_on_single_line":"ignore"
    },
    "entity_003": {
      "style":"allow_comment"
    },
    "entity_017":{
      "compact_alignment": false,
      "comment_line_ends_group": false,
      "blank_line_ends_group": false,
      "separate_generic_port_alignment": true,
    },
    "function_006": {
      "style":"allow_comment"
    },
    "generate_004": {
      "style":"allow_comment"
    },
    "generate_011":{
      "action":"add"
    },
    "generate_017":{
      "disable":false,
    },
    "instantiation_004":{
      "style":"allow_comment"
    },
    "instantiation_033":{
      "action":"remove"
    },
    "instantiation_034":{
      "method":"entity",
      "style":"entity",
    },
    "instantiation_601":{
      "prefixes": ["uut", "inst_"],
      "disable":false,
    },
    "library_003": {
      "style":"allow_comment",
      "allow_library_clause":true,
    },
    "package_003": {
      "style":"allow_comment"
    },
    "package_body_200": {
      "style":"allow_comment"
    },
    "port_025":{
      "suffixes": ["_i", "_ni", "_o", "_no", "_io", "_nio", "clk", "rst"],
      "disable":false,
    },
    "process_011":{
      "style":"require_blank_line"
    },
    "process_012":{
      "action":"remove"
    },
    "process_015":{
      "style":"allow_comment"
    },
    "process_018":{
      "action":"add"
    },
    "process_021":{
      "style":"no_blank_line"
    },
    "process_026":{
      "style":"no_blank_line"
    },
    "process_027":{
      "style":"no_blank_line"
    },
    "process_029":{
      "clock":"edge"
    },
    "process_036":{
      "disable":false,
    },
    "subtype_004":{
      "prefixes": ["t_"],
      "disable":false,
    },
    "type_010":{
      "style":"allow_comment"
    },
    "type_015":{
      "disable":false,
    },
    "type_011":{
      "style":"no_blank_line"
    },
  },
}
```
with these alignment rules:
```json
{
  "rule":{
    "global":{
      "indentSize":2,
      "comment_line_ends_group":false,
      "blank_line_ends_group":true
    },
  }
}
```
these casing rules:
```json
{
  "rule":{
    "architecture_013":{
      "case": "lower"
    },
    "architecture_014":{
      "case": "lower"
    },
    "constant_004":{
      "case": "upper"
    },
    "entity_008":{
      "case": "lower"
    },
    "entity_012":{
      "case": "lower"
    },
    "function_017":{
      "case": "lower"
    },
    "generic_007":{
      "case": "upper"
    },
    "generate_005":{
      "case": "lower"
    },
    "generate_012":{
      "case": "lower"
    },
    "instantiation_008":{
      "case": "lower"
    },
    "instantiation_009":{
      "case": "lower"
    },
    "port_map_002":{
      "case": "lower"
    },
    "generic_map_002":{
      "case": "upper"
    },
    "instantiation_028":{
      "case": "lower"
    },
    "package_008":{
      "case": "lower"
    },
    "package_010":{
      "case": "lower"
    },
    "port_010":{
      "case": "lower"
    },
    "process_017":{
      "case": "lower"
    },
    "process_019":{
      "case": "lower"
    },
  }
}
```
and completed by the following rules being disabled:
```json
{
  "rule":{
    # Somehow is thown in block comments,
    # see https://github.com/jeremiah-c-leary/vhdl-style-guide/issues/542
    "comment_010":{
      "disable":true
    },
    # This rule checks the bolean expression is enclosed in ().
    "if_002":{
      "disable":true
    },
    # at least a single blank line after the end if
    "if_030":{
      "disable":true
    },
    # blank line before the if
    "if_031":{
      "disable":true
    },
    # This rule checks for default assignments on port declarations.
    # this is actually a fuctionality of VHDL, so we need it!
    "port_012":{
      "disable":true
    },
    # This rule checks for a blank line below the begin keyword.
    # Decided to be disabled, see #162
    "process_022":{
      "disable":true
    },
    # This rule checks for a blank line above the end process keyword.
    # Decided to be disabled, see #162
    "process_023":{
      "disable":true
    },
    # This rule checks for a single signal per line in a sensitivity list that is not the last one.
    "process_030":{
      "disable":true
    },
    # This rule checks for comments within multiline sequential statements.
    "sequential_006":{
      "disable":true
    },
    # This rule checks for a blank line below the type declaration.
    # Checking below sth. makes few sense...
    "type_011":{
      "disable":true
    },
    # This rule checks for comments in multiline variable assignments.
    "variable_assignment_006":{
      "disable":true
    },
    # how does one dare to tag this as an error ...
    "with_001":{
      "disable":true
    },
  }
}
```

Maybe this would provoke the error.

If not, I would try to get you more context on the source file it crashes on.

**Comment by jeremiah-c-leary** [comment] 2021-03-31 13:13
Hey @staerz ,

I tried your configurations and I was not able to get my snippet to fail.

--Jeremy

**Comment by samdejong86** [comment] 2021-04-01 16:20
Hi @jeremiah-c-leary 

I'm working with @staerz and first found this issue. Here's an example that crashes for me. I've hacked it down to the minimum required to make it fail

```vhdl
entity foo is
  generic (
    --! enable downlink path
    blah                 : boolean := true
  );
  port (
    -- Clocks
    --! Downlink datapath clock (MGT tx clock)
    clk     : in    std_logic                        := '0';
    -- Control
    ctr  : out   std_logic
  );
end entity foo;


--! Implementation of lpGBT_top
architecture behavioral of foo is

begin

    inst_dummy : entity lib.module
    port map (
      -- Clocks
      clk   => clk
      --
      -- Dummy comment
      --
      data_i => data_i
    );


  gen_bar : if FOOBAR generate


    inst_something : entity work.something
    generic map (
      C_CLOCKRATIO  => 8,
      C_OUTPUTWIDTH => 32
    )
    port map (
      -- Clocks
      clk_i               => clk,
      rdy_o               => Ready_o

    );

  end generate gen_bar;

end architecture behavioral;


```

**Comment by jeremiah-c-leary** [comment] 2021-04-01 17:23
Hey @samdejong86,

Thanks for the code.  I was able to recreate the error on my side and reduce it further:
```vhdl
  1
  2 architecture behavioral of foo is
  3
  4 begin
  5
  6     inst_dummy : entity lib.module
  7     port map (
  8       --
  9       -- Dummy comment
 10       --
 11       data_i => data_i
 12     );
 13
 14     -- Comment
 15
 16 end architecture behavioral;
```
It is the comment on line 14 that is causing the issue.  I will investigate.  It will be later tonight though.

--Jeremy

**Comment by jeremiah-c-leary** [comment] 2021-04-01 17:41
Hey @samdejong86,

I just pushed an update for this issue.  When you get a chance, could you validate it on your end.

Thanks,

--Jeremy

**Comment by samdejong86** [comment] 2021-04-01 17:55
Thanks @jeremiah-c-leary , I can confirm that it works.

**Comment by jeremiah-c-leary** [comment] 2021-04-01 17:56
Awesome!!! I will close this ticket.

**Closed by jeremiah-c-leary** 2021-04-01 17:56 UTC
Labels: bug
