### ISSUE TITLE
whitespace_011 on left side of assignement

### ISSUE THREAD

**Issue by oletf** [jeremiah-c-leary/vhdl-style-guide#801] opened 2022-07-13 10:03 UTC
could it be possible to have `whitespace_011` rule also working on left side of assignments ?

```vhdl
        for i in b'range loop
          a(i*2) <= b(i);
        end loop;
```
into
```vhdl
        for i in b'range loop
          a(i * 2) <= b(i);
        end loop;
```

thanks forward

**Comment by oletf** [comment] 2022-07-15 09:29
Hi,

I just noticed that the rule is actually applied on the left side only for `+` and `-`, 
while absence of space around `*` `/` and `**` all stay as they are.

**Comment by jeremiah-c-leary** [comment] 2022-07-15 11:29
Hey @oletf,

Thanks for the update.  It will help me narrow down where the issue is.

--Jeremy

**Comment by jeremiah-c-leary** [comment] 2022-07-15 12:22
Hey @oletf,

I just pushed an update to this issue to the issue-801 branch.  When you get a chance could you check if it works for you.

I will plan to close this issue on July 22nd if I do not hear back from you.

Thanks,

--Jeremy

**Comment by oletf** [comment] 2022-07-15 12:44
working all good on my side,
can merge and close 👍 !

**Comment by jeremiah-c-leary** [comment] 2022-07-15 12:45
Sweet!!!

I will merge this.

--Jeremy

**Closed** 2022-07-15 12:46 UTC
Labels: enhancement
