### ISSUE TITLE
Constant capitalization of ports

### ISSUE THREAD

**Issue by rugebiker** [jeremiah-c-leary/vhdl-style-guide#656] opened 2021-10-29 12:10 UTC
Hi, 
Rules entity_600 and architecture_600 define constant capitalization of generics. It would be nice if we can have also rules for the constant capitalization of ports.

Thanks!
--Ruben

**Comment by jeremiah-c-leary** [comment] 2021-10-30 01:12
Hey,

I think this is a duplicate of issue #554.  Could you check that issue and see if it matches what you are asking for?

Thanks,

--Jeremy

**Comment by rugebiker** [comment] 2021-11-02 13:46
Hi @jeremiah-c-leary , indeed is the same :)  My apologies for reporting something that was already reported.

**Closed** 2021-11-02 14:16 UTC
Labels: enhancement
